[package]
name = "rapier-with-dioxus"
version = "0.0.1"
edition = "2021"
license = "MIT"
description = "rapier for dioxus"

[dependencies]

dioxus = { version = "0.5", features = ["web"] }

# Debug
dioxus-logger = "0.5.1"
rapier2d = { version = "0.22.0", features = ["simd-stable"] }
